db_config:
  uri: mongodb://localhost:27017
  database: angle_bracket

plugins:
  - mongeasy_plugin.beforesave.BeforeSavePlugin
  # - sample_plugins.connection_plugin.SampleConnectionPlugin
  # - sample_plugins.delete_plugin.SampleDeletePlugin
  # - sample_plugins.init_plugin.SampleInitPlugin
  # - sample_plugins.query_plugin.SampleQueryPlugin
  # - sample_plugins.save_plugin.SampleSavePlugin
  # - sample_plugins.validator_plugin.SampleValidatePlugin
